### ISSUE TITLE
connectWithAuth hangs on invalid orgId/User

### ISSUE THREAD

**Issue by antempus** [pozil/pub-sub-api-node-client#15]
Ran into an issue when I accidentally swapped the 3rd and 4th param for `connectWithAuth` , where by the client wouldn't fail to connect nor throw an error and sat there indefinitely. This stall lasted for a decent amount of time, minutes, after stopping the attempt to debug internally.

```javascript
   await client.connectWithAuth(
            accessToken,
            configinstanceUrl,
            // following two were swapped
            orgId,
            user
        );
```

**Comment by pozil** [comment]
Good to know, thanks for the feedback.
I added extra checks for those parameters and released a new version.
