### ISSUE TITLE
SALESFORCE_TOKEN should not be required 

### ISSUE THREAD

**Issue by eltoroit** [pozil/pub-sub-api-node-client#19]
I am using a `SALESFORCE_AUTH_TYPE=username-password` to connect to a scratch org where my user's profile has the IP range configured from 0.0.0.0 to 255.255.255.255 so that I am required to provide the `SALESFORCE_TOKEN`. But this library errors out if I leave it blank

I had to break my password "abc123" (not my real password) into:   

```
SALESFORCE_PASSWORD=abc
SALESFORCE_TOKEN=123
```

**Comment by pozil** [comment]
Good catch. I just released a fix to make the token optional.
