### ISSUE TITLE
Getting the n-1 replayId

### ISSUE THREAD

**Issue by kunalrgarg** [pozil/pub-sub-api-node-client#22]
I'm looking to get the most recent replayId instead of the earliest. For example, instead of `subscribeFromEarliestEvent` is there a way to get `subscribeFromReplayId('/data/AccountChangeEvent',5,**-1**)` or something like `subscribeFromLatestEvent` if it existed? Alternatively, is there a way to provide a commitTimestamp or DateTime object as the starting point for the events? The purpose of this is to ensure that we're subscribing to the topicName at the correct event in the case that a service ever experiences down time and we didn't capture the replayId during this period.

providing a negative replayId doesn't play well with `new Buffer().writeBigU_Int64BE`.

Looking at the documentation, it seems like we'd be able to receive the empty FetchResponse with the most recent replayId after 270 seconds: https://developer.salesforce.com/docs/platform/pub-sub-api/references/methods/subscribe-rpc.html, but it doesn't seem to emit with `eventEmitter.on('data', (event) => {});` after that time period.

**Comment by pozil** [comment]
@kunalrgarg you can't use relative replay ID directly but the good news is that I just released support for the keep alive message. This means that if you wait (generally less than the 270) seconds you can get the latest replay ID via the `keepalive` message sent by the [PubSubEventEmitter](https://github.com/pozil/pub-sub-api-node-client#pubsubeventemitter).

You can do something like this:
```js
eventEmitter.once('keepalive', (data) => {
  // use the received data.lastReplayId for your logic
});
```
