### ISSUE TITLE
Type of `numRequested` should be a number

### ISSUE THREAD

**Issue by if0s** [pozil/pub-sub-api-node-client#24]
# Small Bug Report

## Description
If you subscribe to an event using `numRequested` as a string, it will not trigger the `lastevent` due to [strict equality](https://github.com/pozil/pub-sub-api-node-client/blob/7d3ae017484ff40b8699bbb5689efbefa088ab12/src/client.js#L335C1-L335C4) comparison, but it will still emit the specified number of events.
To avoid misunderstanding, it's better to check the type of `numRequested`, and either throw an error or try to parse it as a number.

## Version
3.2.2

**Comment by pozil** [comment]
Hi @if0s thanks for reporting this, it's indeed a bug.
I fixed it in the latest version v3.2.3.
