### ISSUE TITLE
readBigUInt64BE is not a function

### ISSUE THREAD

**Issue by chandra2ravi** [pozil/pub-sub-api-node-client#3]
Hi,

I'm getting the below error while running the app.

TypeError: data.latestReplayId.readBigUInt64BE is not a function
![image](https://user-images.githubusercontent.com/93057/198420166-35949869-4234-4b2c-830a-005fe65f8c6a.png)

Thanks
Ravi

**Comment by pozil** [comment]
Hi @chandra2ravi, are you using the right node version?
This project supports node v16.

**Comment by chandra2ravi** [comment]
Hi Philippe,
Thanks for the quick reply, updated it to the latest version and fixed the issue.

Thanks
Ravi
