### ISSUE TITLE
Error subscribing from a replay Id

### ISSUE THREAD

**Issue by AlbertHernandez** [pozil/pub-sub-api-node-client#4]
Hi team!

I am trying to connect to salesforce using this new amazing communication, everything was working fine, however, when we started trying to connect from a previous replay id we started to receive some errors.

Reading the [documentation](https://developer.salesforce.com/docs/platform/pub-sub-api/references/methods/subscribe-rpc.html) it indicates that for subscribing from a replay id we need to specify the replay preset and the replay id.

> The replay option consists of a combination of replay_preset and replay_id values in the first FetchRequest received from a client.

So what we have done is add to the subscribe requests those 2 new options

```js
const subscribeRequest = {
    topicName,
    numRequested: PUB_SUB_EVENT_RECEIVE_LIMIT,

    // new options for connecting from the replay id
    replayId: "12907414",
    replayPreset: 2
};
```

However, now we are receiving an error

`sfdc.platform.eventbus.grpc.subscription.fetch.replayid.corrupte`

Checking the documentation, this error says:
> The Replay ID validation failed. Ensure that the replay_id field value in FetchRequest is valid and refers to an event that is within the retention window.

But we know that this replay id is valid because if we use it with the previous communication everything is working and also this event was sent on the same day.

@pozil Do you have some idea about what can be happening?

**Comment by pozil** [comment]
Sorry for the delay, I was on vacation in the meantime. Looking at this now.

**Comment by pozil** [comment]
Pretty sure that has to with the encoding of the replay ID.
When we decode it, we have to run `data.latestReplayId.readBigUInt64BE()` to obtain it in its classical numeric form (like 12907414).
We need to apply the reverse operation when subscribing.

I'm looking at something like this but this doesn't quite work:
```js
function encodeReplayId(replayId) {
    const buf = Buffer.allocUnsafe(8);
    buf.writeBigUInt64BE(BigInt(replayId), 0);
    return buf.toString();
}
```
I'm getting this error:
> gRPC stream error:  {"code":13,"details":"Request message serialization failure: invalid encoding","metadata":{}}

I'm going to dig a bit more...

**Comment by pozil** [comment]
Hi @AlbertHernandez. I just solved the issue (I didn't need the call to `toString` as I'm passing a byte buffer directly in the subscription).
I released an update to the client with an `encodeReplayId(replayId)` and a `decodeReplayId(encodedReplayId)` method in `eventParser` and I added a note in the readme.

I'll close the issue but let me know I need to reopen it.
