### ISSUE TITLE
Mismatch between `EventEmitter` and `PubSubEventEmitter`

### ISSUE THREAD

**Issue by robbiefryers** [pozil/pub-sub-api-node-client#42]
Hi thanks for the amazing lib. Just a quick question regarding the flow control section in the readme. There is a type mismatch between what `client.subscribe` returns (plain `EventEmitter`) and what `client.requestAdditionalEvents` expects for its first arg: (`PubSubEventEmitter`). Looking through the source it looks like `subscribe` always returns an `PubSubEventEmitter`.

```
try {
    
// This returns a plain 'EventEmitter'
    const eventEmitter = await client.subscribe('/data/AccountChangeEvent', 10);


    eventEmitter.on('lastevent', () => {
        // this is expecting a PubSubEventEmitter 
        client.requestAdditionalEvents(eventEmitter, 10);
    });
} catch (error) {
    console.error(error);
}
```

**Comment by pozil** [comment]
Hi @robbiefryers, thanks for the feedback and for catching this. The correct type is indeed `PubSubEventEmitter`.
I've released a new version with a fix.
