### ISSUE TITLE
Bug in requesting additional events for infinite event request

### ISSUE THREAD

**Issue by alice-watershed** [pozil/pub-sub-api-node-client#49]
If you open an infinite connection, it only requests 200 events before closing the connection. The sequence of events is:
1. Open a connection and request 100 events
2. Receive 100 events
3. Hit the `receivedEventCount === requestedEventCount` [if statement here](https://github.com/pozil/pub-sub-api-node-client/blob/d1af726d9f6803fa9dbe6390a708e3415846315a/src/client.js#L446)
4. Request 100 additional events. `receivedEventCount` is not reset to 0 because the [code incorrectly sets](https://github.com/pozil/pub-sub-api-node-client/blob/d1af726d9f6803fa9dbe6390a708e3415846315a/src/client.js#L534C1-L534C9) `subscription.receivedEventCount = 0`, instead of `subscription.info.receivedEventCount = 0`
5. Receive 100 events
6. At this point, `receivedEventCount = 200` and `requestedEventCount = 100` so we never hit the if statement again
7. Close the connection because we received the last event

Incorrect:
```
requestAdditionalEvents(topicName, numRequested) {
  .........
        // Request additional events
        subscription.receivedEventCount = 0;
        subscription.requestedEventCount = numRequested;
  .........
    }
```
Correct:
```
requestAdditionalEvents(topicName, numRequested) {
  .........
        // Request additional events
        subscription.info.receivedEventCount = 0;
        subscription.info.requestedEventCount = numRequested;
  .........
    }
```

**Comment by pozil** [comment]
Great catch! Thanks for the detailed description and the source of the error. I fixed it in v5.0.2.
