### ISSUE TITLE
Support PublishStream / Problems with high load

### ISSUE THREAD

**Issue by yannickpoggel** [pozil/pub-sub-api-node-client#51]
Hi @pozil,

we are currently running into errors, when load is a little bit higher (>80 requests in sequence) and we are hitting the salesforce tenantIdRateLimiter: 

Service-Logs: "Error: 8 RESOURCE_EXHAUSTED: The service received too many connections and doesn't have the resources to accept new connections." 
Salesforce-Logs: "The service received too many connections and doesn't have the resources to accept new connections" 

The salesforce support suggested to use PublishStream instead of Publish.

PublishStream in .proto: https://github.com/pozil/pub-sub-api-node-client/blob/main/pubsub_api.proto#L400
PublishStream Salesforce Docs: https://developer.salesforce.com/docs/platform/pub-sub-api/references/methods/publishstream-rpc.html?q=publish

**Comment by pozil** [comment]
Hi @yannickpoggel thanks for reaching out. Supporting streaming publish is indeed on my todo list. I just released managed event subscriptions and I'll work on streaming publish next.

**Comment by pozil** [comment]
Hi @yannickpoggel, I implemented batch event publishing in the latest version.
