### ISSUE TITLE
Changed fields array does not contain correct changed fields

### ISSUE THREAD

**Issue by ValeriyRCG** [pozil/pub-sub-api-node-client#8]
I installed this as a package in a brand new project and I seem to be having issues.
The changeFields array does not contain the actual fields that were changed. I changed the website on an account record as an example and I receive AnnualRevenue and TickerSymbol fields in the changedFields but when I look at the payload itself it shows the website and lastmodifieddate fields as the ones with actual changed data.
Here is a preview of what I am looking at, I promise I did not edit this in any way. I replace the sfids just in case.
```json
{
  "replayId": 29718,
  "payload": {
    "ChangeEventHeader": {
      "entityName": "Account",
      "recordIds": [
        "sfid"
      ],
      "changeType": "UPDATE",
      "changeOrigin": "com/salesforce/api/soap/57.0;client=SfdcInternalAPI/",
      "transactionKey": "0002d5d2-d8a7-1ba3-9743-9f168046112b",
      "sequenceNumber": 1,
      "commitTimestamp": 1674679214000,
      "commitNumber": 11101546841929,
      "commitUser": "sfid",
      "nulledFields": [],
      "diffFields": [],
      "changedFields": [
        "AnnualRevenue",
        "TickerSymbol"
      ]
    },
    "Name": null,
    "Type": null,
    "RecordTypeId": null,
    "ParentId": null,
    "BillingAddress": null,
    "ShippingAddress": null,
    "Phone": null,
    "Fax": null,
    "AccountNumber": null,
    "Website": {
      "string": "goog.com"
    },
    "Sic": null,
    "Industry": null,
    "AnnualRevenue": null,
    "NumberOfEmployees": null,
    "Ownership": null,
    "TickerSymbol": null,
    "Description": null,
    "Rating": null,
    "Site": null,
    "OwnerId": null,
    "CreatedDate": null,
    "CreatedById": null,
    "LastModifiedDate": {
      "long": 1674679214000
    },
    "LastModifiedById": null,
    "PersonContactId": null,
    "PersonMailingAddress": null,
    "PersonOtherAddress": null,
    "PersonMobilePhone": null
}
```

As you can see from my payload, it does not match up with what is in the changedFields array. Is there some sort of setting or configuration issue on my end that is making this happen?

**Comment by pozil** [comment]
Hi @ValeriyRCG, this is likely a bug as there's no configuration that could lead to such an issue.
I fixed a similar problem earlier. Can you tell me which version of the client you're using?
If it's not the latest, can you upgrade and let me know if the issue persists.

**Comment by ValeriyRCG** [comment]
Hi @pozil I am using the latest client package version. These are the dependencies in my package json.
`"dependencies": {
    "jsforce": "^1.11.0",
    "salesforce-pubsub-api-client": "^2.3.0"
  }`

Could it be because I have person accounts enabled?

**Comment by pozil** [comment]
I haven't tested with person accounts and I don't know if this can introduce some extra complexity. The truth is that I'm struggling with the way change fields are encoded.
I'll keep this issue open for now but I'm a bit short on time to diagnose this at the moment, sorry.

**Comment by ValeriyRCG** [comment]
Thank you @pozil. I will try to fix this on my end and maybe I can submit a solution if I find it myself.

**Comment by pozil** [comment]
Hi @ValeriyRCG sorry for the delay but I managed to dedicate some time to this and finally found the issue. Please use the latest version of the library for a fix.
