### ISSUE TITLE
Add logic to simplify Avro decoding and field access

### ISSUE THREAD

**Issue by pozil** [pozil/pub-sub-api-node-client#9]
Event payloads looks like this after being decoded by Avro:
```js
{
    Name: { string : "My name" },
    LastModifiedDate: { long: 1675168622000 }
}
```

It would be nice to strip the intermediate type properties and produce something like this:
```js
{
    Name: "My name",
    LastModifiedDate: 1675168622000
}
```

**Comment by soileaud** [comment]
This was an issue for us, and I came up with this solution. I'm curious what others are doing. This worked for Platform Events, haven't tested change data capture since we don't use it. 

```java
Object.entries(payload).forEach(([key, value]) => {
    if (value && typeof value === 'object') {
        payload[key] = value[Object.keys(value)[0])
    }
````

**Comment by pozil** [comment]
Thanks for the lead @soileaud. The [implementation](https://github.com/pozil/pub-sub-api-node-client/blob/main/src/eventParser.js#L49) turned out to be a bit more complex because of compound types but it's now part of v3.0.0.
